In [6]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)
    
print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


In [8]:
import numpy as np
a = range(1, 10)
b = np.array(a)
print(a[0])
print(b[0])
print(b.shape)

1
1
(9,)


In [9]:
np.random.random((2,2))

array([[ 0.69962895,  0.41486124],
       [ 0.29721912,  0.01810776]])

In [13]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [14]:
a[2, :] = [11,12,13,14]
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]]


In [15]:
a[2] = [15,16,17,18]
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [15 16 17 18]]


In [18]:
a[[0,1,0], 2]

array([3, 7, 3])

In [19]:
a[[0,1,2,],2] = 3

In [20]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  3,  8],
       [15, 16,  3, 18]])

In [27]:
X = np.array([[[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]], [[111,222,333],[444,555,666]], [[411,422,433],[144,155,166]]])
X

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[ 11,  22,  33],
        [ 44,  55,  66]],

       [[111, 222, 333],
        [444, 555, 666]],

       [[411, 422, 433],
        [144, 155, 166]]])

In [28]:
X.shape

(4, 2, 3)

In [30]:
np.sum(X, axis = (1, 2))

array([  21,  231, 2331, 1731])

In [32]:
np.sum(a, axis = 1)

array([10, 22, 52])

In [34]:
np.sum(a, axis = 0)

array([21, 24,  9, 30])

In [35]:
a.shape

(3, 4)

In [36]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  3,  8],
       [15, 16,  3, 18]])

In [37]:
a.T

array([[ 1,  5, 15],
       [ 2,  6, 16],
       [ 3,  3,  3],
       [ 4,  8, 18]])

In [38]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)
y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [42]:
a = np.array([[1,2], [3,4]])
b = np.array([3,4])
a + b

array([[4, 6],
       [6, 8]])

In [43]:
a = np.array([[1,2], [3,4]])
b = np.array([[3,4]])
a + b

array([[4, 6],
       [6, 8]])

In [44]:
v = np.array([1,2,3])
w = np.array([4,5])

In [45]:
np.reshape(v, (3, 1)) * w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [46]:
x = np.array([[1,2,3], [4,5,6]])
x + v

array([[2, 4, 6],
       [5, 7, 9]])

In [47]:
(x.T + w).T

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [49]:
x + w.T

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [50]:
x + np.reshape(w, (2, 1))

array([[ 5,  6,  7],
       [ 9, 10, 11]])